version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - "80:80"           # Puerto HTTP para onixracing.com
      # - "8181:8181"       # Puerto para Proxy Manager
    volumes:
      - D:/SERVIDORES/nginx/conf:/etc/nginx/conf.d
      - D:/SERVIDORES/nginx/logs:/var/log/nginx
    networks:
      - onixracing-network

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    ports:
      - "8089:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - D:/SERVIDORES/wordpress/html:/var/www/html
    networks:
      - onixracing-network

  db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - D:/SERVIDORES/wordpress/db:/var/lib/mysql
    networks:
      - onixracing-network

networks:
  onixracing-network:
    driver: bridge